version: '3.9'

volumes:
  postgres_data:
    driver: local

services:
  java-postgres:
    restart: unless-stopped
    image: postgres:latest
    container_name: java-postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: javauser
      POSTGRES_PASSWORD: javapass

  java-redis:
    restart: unless-stopped
    image: redis:latest
    container_name: java-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
