name: CI

on:
  push:
    branches:
      - master
      - develop
      - hotfix/**
      - feature/**
      - renovate/**

jobs:
  github-actions:
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Ubuntu
            version: ubuntu-latest
        java:
          - name: Corretto 17
            distribution: corretto
            version: 17
        project:
          - name: APIs - Spring Boot
            working-directory: ./apis/spring-boot
          - name: Messages - ActiveMQ - Producer
            image-name: active-producer
            working-directory: ./messages/active/producer
          - name: Messages - ActiveMQ - Consumer
            image-name: active-consumer
            working-directory: ./messages/active/consumer
          - name: Messages - gRPC - Producer
            image-name: grpc-producer
            working-directory: ./messages/grpc/producer
          - name: Messages - gRPC - Consumer
            image-name: grpc-consumer
            working-directory: ./messages/grpc/consumer
          - name: Messages - Kafka - Producer
            image-name: kafka-producer
            working-directory: ./messages/kafka/producer
          - name: Messages - Kafka - Consumer
            image-name: kafka-consumer
            working-directory: ./messages/kafka/consumer
          - name: Messages - RabbitMQ - Producer
            image-name: rabbit-producer
            working-directory: ./messages/rabbit/producer
          - name: Messages - RabbitMQ - Consumer
            image-name: rabbit-consumer
            working-directory: ./messages/rabbit/consumer
          - name: Messages - Redis - Producer
            image-name: redis-producer
            working-directory: ./messages/redis/producer
          - name: Messages - Redis - Consumer
            image-name: redis-consumer
            working-directory: ./messages/redis/consumer
    name: ${{ matrix.os.name }} - ${{ matrix.java.name }} - ${{ matrix.project.name }}
    runs-on: ${{ matrix.os.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: ${{ matrix.java.distribution }}
          java-version: ${{ matrix.java.version }}
      - name: Build JAR
        run: ./gradlew jar
        working-directory: ${{ matrix.project.working-directory }}\
